# Generated by Django 3.2.16 on 2022-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAVELAPP1', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pics')),
                ('name1', models.CharField(max_length=250)),
                ('description1', models.TextField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
